project:
  type: website
  output-dir: docs

website:
  open-graph: true
  title: "Joan Tan"
  favicon: images/joanicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.scss
    toc: true
    page-layout: full
    mainfont: Nunito

editor: visual
