project:
  type: website
  output-dir: docs

website:
  open-graph: true
  site-url: https://joantan.org/
  title: "Dr. Joan Tan"
  favicon: images/joanicon.png
  google-analytics: 
    tracking-id: "G-D2D80R1TVV"
    anonymize-ip: true
  navbar:
    logo: images/joanicon.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - R.qmd
      - Python.qmd
      - Statistics.qmd
      - Resources.qmd
      - publication.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/joan-tan-532a6765/
        target: _blank
      - icon: github
        href: https://github.com/joannytan
        target: _blank
      - icon: envelope
        href: mailto:joan.tan@monash.edu
  page-footer: 
    background: light
    left: Copyright 2024, Joan Tan
    # right: 
    #   - icon: github
    #     href: https://github.com/samanthacsik
    #   - icon: twitter
    #     href: https://twitter.com/SamanthaCsik
    #   - icon: linkedin
    #     href: https://www.linkedin.com/in/samanthacsik/
    #   - icon: envelope
    #     href: mailto:scsik@ucsb.edu
  # reader-mode: true
  # repo-url: https://github.com/samanthacsik/samanthacsik-quarto-website
  # repo-actions: [edit, issue]

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true

editor: visual

  