project:
  type: website
  output-dir: docs

website:
  open-graph: true
  title: "Joan Tan"
  favicon: images/joanicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publication.qmd
  page-footer: 
    background: light
    left: Copyright 2024, Dr. Joan Tan
    # right: 
    #   - icon: github
    #     href: https://github.com/samanthacsik
    #   - icon: twitter
    #     href: https://twitter.com/SamanthaCsik
    #   - icon: linkedin
    #     href: https://www.linkedin.com/in/samanthacsik/
    #   - icon: envelope
    #     href: mailto:scsik@ucsb.edu
  # reader-mode: true
  # repo-url: https://github.com/samanthacsik/samanthacsik-quarto-website
  # repo-actions: [edit, issue]

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    # css: styles.css
    mainfont: Nunito
    toc: true

editor: visual

  